language: node_js
node_js:
  - node
  - lts/*
  - 10
  - 12
before_install:
  - npm i -g npm@7.11.1
npm_args: --no-optional --no-fund
dist: bionic
os: linux
after_success: f [ ${NV:0:3} == "lts" ] ; then npm run coverage-report; fi